set_property PACKAGE_PIN V13 [get_ports {led[7]}]
set_property PACKAGE_PIN V3 [get_ports {led[6]}]
set_property PACKAGE_PIN W3 [get_ports {led[5]}]
set_property PACKAGE_PIN U3 [get_ports {led[4]}]
set_property PACKAGE_PIN P3 [get_ports {led[3]}]
set_property PACKAGE_PIN N3 [get_ports {led[2]}]
set_property PACKAGE_PIN P1 [get_ports {led[1]}]
set_property PACKAGE_PIN L1 [get_ports {led[0]}]

set_property PACKAGE_PIN R2 [get_ports {switch[0]}]
set_property PACKAGE_PIN T1 [get_ports {switch[1]}]
set_property PACKAGE_PIN U1 [get_ports {switch[2]}]
set_property PACKAGE_PIN W2 [get_ports {switch[3]}]
set_property PACKAGE_PIN R3 [get_ports {switch[4]}]
set_property PACKAGE_PIN T2 [get_ports {switch[5]}]
set_property PACKAGE_PIN T3 [get_ports {switch[6]}]
set_property PACKAGE_PIN V2 [get_ports {switch[7]}]

set_property PACKAGE_PIN W4 [get_ports {an[3]}]
set_property PACKAGE_PIN V4 [get_ports {an[2]}]
set_property PACKAGE_PIN U4 [get_ports {an[1]}]
set_property PACKAGE_PIN U2 [get_ports {an[0]}]

set_property PACKAGE_PIN W7 [get_ports {cat[6]}]
set_property PACKAGE_PIN W6 [get_ports {cat[5]}]
set_property PACKAGE_PIN U8 [get_ports {cat[4]}]
set_property PACKAGE_PIN V8 [get_ports {cat[3]}]
set_property PACKAGE_PIN U5 [get_ports {cat[2]}]
set_property PACKAGE_PIN V5 [get_ports {cat[1]}]
set_property PACKAGE_PIN U7 [get_ports {cat[0]}]

set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN U18 [get_ports rst]
set_property PACKAGE_PIN A14 [get_ports freq]
set_property PACKAGE_PIN A15 [get_ports gain]
set_property PACKAGE_PIN B16 [get_ports shutdown]
#set_property PACKAGE_PIN B18 [get_ports sdata_in]
#set_property PACKAGE_PIN A18 [get_ports sdata_out]

set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {switch[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {cat[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cat[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cat[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cat[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cat[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cat[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cat[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports freq]
set_property IOSTANDARD LVCMOS33 [get_ports gain]
set_property IOSTANDARD LVCMOS33 [get_ports shutdown]
#set_property IOSTANDARD LVCMOS33 [get_ports sdata_in]
#set_property IOSTANDARD LVCMOS33 [get_ports sdata_out]


